DROP TABLE if exists CLIENTE;

CREATE TABLE CLIENTE
(
        ID_USUARIO VARCHAR(254) NOT NULL,
        RFC VARCHAR(13) NOT NULL,
        RAZON_SOCIAL TEXT NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY (ID_USUARIO);
ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_UK" UNIQUE (RFC);
ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_USUARIO_FK1" FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)  ON UPDATE NO ACTION ON DELETE NO ACTION;
CREATE INDEX CLIENTE_FK1IDX ON CLIENTE USING BTREE (ID_USUARIO);
