DROP TABLE if exists CLIENTE;
DROP FUNCTION if exists char_2_bigint(TEXT);

CREATE TABLE CLIENTE
(
        ID_USUARIO VARCHAR(254) NOT NULL,
        RFC VARCHAR(13) NOT NULL,
        RAZON_SOCIAL TEXT NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY (ID_USUARIO);
ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_UK" UNIQUE (RFC);
ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_USUARIO_FK1" FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)  ON UPDATE NO ACTION ON DELETE NO ACTION;
CREATE INDEX CLIENTE_FK1IDX ON CLIENTE USING BTREE (ID_USUARIO);

create function char_2_bigint(textVal text) returns BIGINT as $$
DECLARE
    result  BIGINT;
BEGIN
    EXECUTE 'SELECT x''' || substr(md5(textVal),1,16) || '''::bigint' INTO result;
    RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;