DROP TABLE if exists CLIENTE;

CREATE TABLE CLIENTE
(
        ID_CLIENTE SERIAL NOT NULL,
        NOMBRE TEXT NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY (ID_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT "CLIENTE_UK" UNIQUE (NOMBRE);