package mx.com.gunix.ui.vaadin.view.adminapp.aplicacion.components;

import mx.com.gunix.framework.security.domain.Rol;
import mx.com.gunix.framework.ui.vaadin.component.GunixBeanFieldGroup;
import mx.com.gunix.framework.ui.vaadin.view.AbstractGunixView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Window;

public class RolForm extends CustomComponent {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private FormLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;

	@AutoGenerated
	private Button cancelarButton;

	@AutoGenerated
	private Button aceptarButton;

	@AutoGenerated
	private TextField descripcion;

	@AutoGenerated
	private TextField idRol;

	private BeanFieldGroup<Rol> rolFieldGroup;

	private static final long serialVersionUID = 1L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * 
	 * @param window
	 */
	public RolForm(Window window) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		rolFieldGroup = new BeanFieldGroup<Rol>(Rol.class);
		rolFieldGroup.setItemDataSource(new Rol());
		rolFieldGroup.bindMemberFields(this);

		aceptarButton.addClickListener(event -> {
			try {
				rolFieldGroup.commit();
				window.close();
			} catch (CommitException e) {
				AbstractGunixView.appendNotification(Type.ERROR_MESSAGE, "Existen errores en el formulario");
			}
		});

		cancelarButton.addClickListener(event -> {
			window.close();
		});

	}

	public Rol getRol() {
		Rol r = rolFieldGroup.getItemDataSource().getBean();
		return r.getIdRol()==null?null:r;
	}

	@AutoGenerated
	private FormLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new FormLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// idModulo
		idRol = new TextField();
		idRol.setCaption("Id Rol");
		idRol.setImmediate(false);
		idRol.setWidth("-1px");
		idRol.setHeight("-1px");
		idRol.setInvalidAllowed(false);
		idRol.setNullRepresentation("");
		mainLayout.addComponent(idRol);
		
		// descripcion
		descripcion = new TextField();
		descripcion.setCaption("Descripción");
		descripcion.setImmediate(false);
		descripcion.setWidth("-1px");
		descripcion.setHeight("-1px");
		descripcion.setInvalidAllowed(false);
		descripcion.setNullRepresentation("");
		mainLayout.addComponent(descripcion);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// aceptarButton
		aceptarButton = new Button();
		aceptarButton.setCaption("Aceptar");
		aceptarButton.setImmediate(true);
		aceptarButton.setWidth("-1px");
		aceptarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(aceptarButton);
		
		// cancelarButton
		cancelarButton = new Button();
		cancelarButton.setCaption("Cancelar");
		cancelarButton.setImmediate(true);
		cancelarButton.setWidth("-1px");
		cancelarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(cancelarButton);
		
		return horizontalLayout_1;
	}

	public void setRol(Rol rol) {
		rolFieldGroup = new GunixBeanFieldGroup<Rol>(Rol.class);
		rolFieldGroup.setItemDataSource(rol);
		rolFieldGroup.bindMemberFields(this);
	}

}
