package mx.com.gunix.ui.vaadin.view.component;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
public class TestComponent extends CustomComponent {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button completeTaskButton;
	@AutoGenerated
	private Button agregaVariableButton;
	@AutoGenerated
	private Table dummyTableVars;
	private static final long serialVersionUID = 1L;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		dummyTableVars.addContainerProperty("Variable", String.class,  null);
		dummyTableVars.addContainerProperty("Valor", String.class,  null);
		dummyTableVars.setEditable(true);
		agregaVariableButton.addClickListener(event->{
			dummyTableVars.addItem();
		});
	}

	public Button getCompleteTaskButton() {
		return completeTaskButton;
	}

	public void setCompleteTaskButton(Button completeTaskButton) {
		this.completeTaskButton = completeTaskButton;
	}

	public Table getDummyTableVars() {
		return dummyTableVars;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// dummyTableVars
		dummyTableVars = new Table();
		dummyTableVars.setImmediate(false);
		dummyTableVars.setWidth("460px");
		dummyTableVars.setHeight("203px");
		mainLayout.addComponent(dummyTableVars);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("460px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// agregaVariableButton
		agregaVariableButton = new Button();
		agregaVariableButton.setCaption("Agregar Variable");
		agregaVariableButton.setImmediate(true);
		agregaVariableButton.setWidth("-1px");
		agregaVariableButton.setHeight("-1px");
		horizontalLayout_1.addComponent(agregaVariableButton);
		
		// completeTaskButton
		completeTaskButton = new Button();
		completeTaskButton.setCaption("Enviar");
		completeTaskButton.setImmediate(true);
		completeTaskButton.setWidth("-1px");
		completeTaskButton.setHeight("-1px");
		horizontalLayout_1.addComponent(completeTaskButton);
		horizontalLayout_1.setComponentAlignment(completeTaskButton, new Alignment(6));
		
		return horizontalLayout_1;
	}

}
